version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      production-major:
        dependency-type: 'production'
        update-types:
          - 'major'
      all-minor-patch:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
    commit-message:
      prefix: 'fix'
      prefix-development: 'chore'
      include: 'scope'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      all-actions:
        patterns:
          - '*'
    commit-message:
      prefix: 'chore'
      include: 'scope'
