version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      production:
        dependency-type: 'production'
      development:
        dependency-type: 'development'
