name: 'OSV'

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']
  schedule:
    - cron: '30 22 * * 5'

permissions:
  actions: read
  security-events: write
  contents: read

jobs:
  scan-pr:
    uses: 'google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@v2.3.5'
